version: '3'
services:
  webrcon:
    build: .
    ports:
      - "127.0.0.1:8080:8080/tcp"
    volumes:
      - .:/code
  redis:
    image: redis
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565/tcp"
    volumes:
      - ./instance/minecraft:/data
    environment:
      - EULA=TRUE
