DROP TABLE IF EXISTS diamonds;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE diamonds (
  number INTEGER NOT NULL,
  timestamp TEXT NOT NULL
);

